branches:
    only:
    - master

chache:
    directories:
    - ~/cache

sudo: required

language: csharp

services:
    - docker

before_install:
    - docker build -t webapp:test .

script:
    - docker run -it --rm -v ~/.nuget/packages webapp:test